#include "common.hpp"
namespace LuaSDL{
	void init_constants(lutok::state & state){
		//SDL_Init
		state.set_field("INIT_TIMER",					SDL_INIT_TIMER);
		state.set_field("INIT_AUDIO",					SDL_INIT_AUDIO);
		state.set_field("INIT_VIDEO",					SDL_INIT_VIDEO);
		state.set_field("INIT_JOYSTICK",				SDL_INIT_JOYSTICK);
		state.set_field("INIT_HAPTIC",					SDL_INIT_HAPTIC);
		state.set_field("INIT_GAMECONTROLLER",			SDL_INIT_GAMECONTROLLER);
		state.set_field("INIT_NOPARACHUTE",				SDL_INIT_NOPARACHUTE);
		state.set_field("INIT_EVERYTHING",				SDL_INIT_EVERYTHING);

		//SDL_WindowFlags
		state.set_field("WINDOW_FULLSCREEN",			SDL_WINDOW_FULLSCREEN);
		state.set_field("WINDOW_OPENGL",				SDL_WINDOW_OPENGL);
		state.set_field("WINDOW_SHOWN",					SDL_WINDOW_SHOWN);
		state.set_field("WINDOW_HIDDEN",				SDL_WINDOW_HIDDEN);
		state.set_field("WINDOW_BORDERLESS",			SDL_WINDOW_BORDERLESS);
		state.set_field("WINDOW_RESIZABLE",				SDL_WINDOW_RESIZABLE);
		state.set_field("WINDOW_MINIMIZED",				SDL_WINDOW_MINIMIZED);
		state.set_field("WINDOW_MAXIMIZED",				SDL_WINDOW_MAXIMIZED);
		state.set_field("WINDOW_INPUT_GRABBED",			SDL_WINDOW_INPUT_GRABBED);
		state.set_field("WINDOW_INPUT_FOCUS",			SDL_WINDOW_INPUT_FOCUS);
		state.set_field("WINDOW_MOUSE_FOCUS",			SDL_WINDOW_MOUSE_FOCUS);
		state.set_field("WINDOW_FULLSCREEN_DESKTOP",	SDL_WINDOW_FULLSCREEN_DESKTOP);
		state.set_field("WINDOW_FOREIGN",				SDL_WINDOW_FOREIGN);

		state.set_field("WINDOWPOS_UNDEFINED_MASK",		SDL_WINDOWPOS_UNDEFINED_MASK);
		state.set_field("WINDOWPOS_CENTERED_MASK",		SDL_WINDOWPOS_CENTERED_MASK);

		//SDL_WindowEventID
		state.set_field("WINDOWEVENT_NONE",				SDL_WINDOWEVENT_NONE);
		state.set_field("WINDOWEVENT_SHOWN",			SDL_WINDOWEVENT_SHOWN);
		state.set_field("WINDOWEVENT_HIDDEN",			SDL_WINDOWEVENT_HIDDEN);
		state.set_field("WINDOWEVENT_EXPOSED",			SDL_WINDOWEVENT_EXPOSED);
		state.set_field("WINDOWEVENT_MOVED",			SDL_WINDOWEVENT_MOVED);
		state.set_field("WINDOWEVENT_RESIZED",			SDL_WINDOWEVENT_RESIZED);
		state.set_field("WINDOWEVENT_SIZE_CHANGED",		SDL_WINDOWEVENT_SIZE_CHANGED);
		state.set_field("WINDOWEVENT_MINIMIZED",		SDL_WINDOWEVENT_MINIMIZED);
		state.set_field("WINDOWEVENT_MAXIMIZED",		SDL_WINDOWEVENT_MAXIMIZED);
		state.set_field("WINDOWEVENT_RESTORED",			SDL_WINDOWEVENT_RESTORED);
		state.set_field("WINDOWEVENT_ENTER",			SDL_WINDOWEVENT_ENTER);
		state.set_field("WINDOWEVENT_LEAVE",			SDL_WINDOWEVENT_LEAVE);
		state.set_field("WINDOWEVENT_FOCUS_GAINED",		SDL_WINDOWEVENT_FOCUS_GAINED);
		state.set_field("WINDOWEVENT_FOCUS_LOST",		SDL_WINDOWEVENT_FOCUS_LOST);
		state.set_field("WINDOWEVENT_CLOSE",			SDL_WINDOWEVENT_CLOSE);

		//Pixel formats
		state.set_field("PIXELFORMAT_UNKNOWN",			SDL_PIXELFORMAT_UNKNOWN);
		state.set_field("PIXELFORMAT_INDEX1LSB",		SDL_PIXELFORMAT_INDEX1LSB);
		state.set_field("PIXELFORMAT_INDEX1MSB",		SDL_PIXELFORMAT_INDEX1MSB);
		state.set_field("PIXELFORMAT_INDEX4LSB",		SDL_PIXELFORMAT_INDEX4LSB);
		state.set_field("PIXELFORMAT_INDEX4MSB",		SDL_PIXELFORMAT_INDEX4MSB);
		state.set_field("PIXELFORMAT_INDEX8",			SDL_PIXELFORMAT_INDEX8);
		state.set_field("PIXELFORMAT_RGB332",			SDL_PIXELFORMAT_RGB332);
		state.set_field("PIXELFORMAT_RGB444",			SDL_PIXELFORMAT_RGB444);
		state.set_field("PIXELFORMAT_RGB555",			SDL_PIXELFORMAT_RGB555);
		state.set_field("PIXELFORMAT_BGR555",			SDL_PIXELFORMAT_BGR555);
		state.set_field("PIXELFORMAT_ARGB4444",			SDL_PIXELFORMAT_ARGB4444);
		state.set_field("PIXELFORMAT_RGBA4444",			SDL_PIXELFORMAT_RGBA4444);
		state.set_field("PIXELFORMAT_ABGR4444",			SDL_PIXELFORMAT_ABGR4444);
		state.set_field("PIXELFORMAT_BGRA4444",			SDL_PIXELFORMAT_BGRA4444);
		state.set_field("PIXELFORMAT_ARGB1555",			SDL_PIXELFORMAT_ARGB1555);
		state.set_field("PIXELFORMAT_RGBA5551",			SDL_PIXELFORMAT_RGBA5551);
		state.set_field("PIXELFORMAT_ABGR1555",			SDL_PIXELFORMAT_ABGR1555);
		state.set_field("PIXELFORMAT_BGRA5551",			SDL_PIXELFORMAT_BGRA5551);
		state.set_field("PIXELFORMAT_RGB565",			SDL_PIXELFORMAT_RGB565);
		state.set_field("PIXELFORMAT_BGR565",			SDL_PIXELFORMAT_BGR565);
		state.set_field("PIXELFORMAT_RGB24",			SDL_PIXELFORMAT_RGB24);
		state.set_field("PIXELFORMAT_BGR24",			SDL_PIXELFORMAT_BGR24);
		state.set_field("PIXELFORMAT_RGB888",			SDL_PIXELFORMAT_RGB888);
		state.set_field("PIXELFORMAT_RGBX8888",			SDL_PIXELFORMAT_RGBX8888);
		state.set_field("PIXELFORMAT_BGR888",			SDL_PIXELFORMAT_BGR888);
		state.set_field("PIXELFORMAT_BGRX8888",			SDL_PIXELFORMAT_BGRX8888);
		state.set_field("PIXELFORMAT_ARGB8888",			SDL_PIXELFORMAT_ARGB8888);
		state.set_field("PIXELFORMAT_RGBA8888",			SDL_PIXELFORMAT_RGBA8888);
		state.set_field("PIXELFORMAT_ABGR8888",			SDL_PIXELFORMAT_ABGR8888);
		state.set_field("PIXELFORMAT_BGRA8888",			SDL_PIXELFORMAT_BGRA8888);
		state.set_field("PIXELFORMAT_ARGB2101010",		SDL_PIXELFORMAT_ARGB2101010);
		state.set_field("PIXELFORMAT_YV12",				SDL_PIXELFORMAT_YV12);
		state.set_field("PIXELFORMAT_IYUV",				SDL_PIXELFORMAT_IYUV);
		state.set_field("PIXELFORMAT_YUY2",				SDL_PIXELFORMAT_YUY2);
		state.set_field("PIXELFORMAT_UYVY",				SDL_PIXELFORMAT_UYVY);
		state.set_field("PIXELFORMAT_YVYU",				SDL_PIXELFORMAT_YVYU);

		//SDL_GLattr
		state.set_field("GL_RED_SIZE",					SDL_GL_RED_SIZE);
		state.set_field("GL_GREEN_SIZE",				SDL_GL_GREEN_SIZE);
		state.set_field("GL_BLUE_SIZE",					SDL_GL_BLUE_SIZE);
		state.set_field("GL_ALPHA_SIZE",				SDL_GL_ALPHA_SIZE);
		state.set_field("GL_BUFFER_SIZE",				SDL_GL_BUFFER_SIZE);
		state.set_field("GL_DOUBLEBUFFER",				SDL_GL_DOUBLEBUFFER);
		state.set_field("GL_DEPTH_SIZE",				SDL_GL_DEPTH_SIZE);
		state.set_field("GL_STENCIL_SIZE",				SDL_GL_STENCIL_SIZE);
		state.set_field("GL_ACCUM_RED_SIZE",			SDL_GL_ACCUM_RED_SIZE);
		state.set_field("GL_ACCUM_GREEN_SIZE",			SDL_GL_ACCUM_GREEN_SIZE);
		state.set_field("GL_ACCUM_BLUE_SIZE",			SDL_GL_ACCUM_BLUE_SIZE);
		state.set_field("GL_ACCUM_ALPHA_SIZE",			SDL_GL_ACCUM_ALPHA_SIZE);
		state.set_field("GL_STEREO",					SDL_GL_STEREO);
		state.set_field("GL_MULTISAMPLEBUFFERS",		SDL_GL_MULTISAMPLEBUFFERS);
		state.set_field("GL_MULTISAMPLESAMPLES",		SDL_GL_MULTISAMPLESAMPLES);
		state.set_field("GL_ACCELERATED_VISUAL",		SDL_GL_ACCELERATED_VISUAL);
		state.set_field("GL_RETAINED_BACKING",			SDL_GL_RETAINED_BACKING);
		state.set_field("GL_CONTEXT_MAJOR_VERSION",		SDL_GL_CONTEXT_MAJOR_VERSION);
		state.set_field("GL_CONTEXT_MINOR_VERSION",		SDL_GL_CONTEXT_MINOR_VERSION);
		state.set_field("GL_CONTEXT_EGL",				SDL_GL_CONTEXT_EGL);
		state.set_field("GL_CONTEXT_FLAGS",				SDL_GL_CONTEXT_FLAGS);
		state.set_field("GL_CONTEXT_PROFILE_MASK",		SDL_GL_CONTEXT_PROFILE_MASK);
		state.set_field("GL_SHARE_WITH_CURRENT_CONTEXT", SDL_GL_SHARE_WITH_CURRENT_CONTEXT);

		//SDL_GLprofile
		state.set_field("GL_CONTEXT_PROFILE_CORE",		SDL_GL_CONTEXT_PROFILE_CORE);
		state.set_field("GL_CONTEXT_PROFILE_COMPATIBILITY", SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
		state.set_field("GL_CONTEXT_PROFILE_ES",		SDL_GL_CONTEXT_PROFILE_ES);

		//SDL_GLcontextFlag
		state.set_field("GL_CONTEXT_DEBUG_FLAG",		SDL_GL_CONTEXT_DEBUG_FLAG);
		state.set_field("GL_CONTEXT_FORWARD_COMPATIBLE_FLAG", SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
		state.set_field("GL_CONTEXT_ROBUST_ACCESS_FLAG", SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG);
		state.set_field("GL_CONTEXT_RESET_ISOLATION_FLAG", SDL_GL_CONTEXT_RESET_ISOLATION_FLAG);

		//SDL_EventType
		state.set_field("QUIT", SDL_QUIT);
		state.set_field("WINDOWEVENT", SDL_WINDOWEVENT);
		state.set_field("SYSWMEVENT", SDL_SYSWMEVENT);
		state.set_field("KEYDOWN", SDL_KEYDOWN);
		state.set_field("KEYUP", SDL_KEYUP);
		state.set_field("TEXTEDITING", SDL_TEXTEDITING);
		state.set_field("TEXTINPUT", SDL_TEXTINPUT);
		state.set_field("MOUSEMOTION", SDL_MOUSEMOTION);
		state.set_field("MOUSEBUTTONDOWN", SDL_MOUSEBUTTONDOWN);
		state.set_field("MOUSEBUTTONUP", SDL_MOUSEBUTTONUP);
		state.set_field("MOUSEWHEEL", SDL_MOUSEWHEEL);
		state.set_field("JOYAXISMOTION", SDL_JOYAXISMOTION);
		state.set_field("JOYBALLMOTION", SDL_JOYBALLMOTION);
		state.set_field("JOYHATMOTION", SDL_JOYHATMOTION);
		state.set_field("JOYBUTTONDOWN", SDL_JOYBUTTONDOWN);
		state.set_field("JOYBUTTONUP", SDL_JOYBUTTONUP);
		state.set_field("JOYDEVICEADDED", SDL_JOYDEVICEADDED);
		state.set_field("JOYDEVICEREMOVED", SDL_JOYDEVICEREMOVED);
		state.set_field("CONTROLLERAXISMOTION", SDL_CONTROLLERAXISMOTION);
		state.set_field("CONTROLLERBUTTONDOWN", SDL_CONTROLLERBUTTONDOWN);
		state.set_field("CONTROLLERBUTTONUP", SDL_CONTROLLERBUTTONUP);
		state.set_field("CONTROLLERDEVICEADDED", SDL_CONTROLLERDEVICEADDED);
		state.set_field("CONTROLLERDEVICEREMOVED", SDL_CONTROLLERDEVICEREMOVED);
		state.set_field("CONTROLLERDEVICEREMAPPED", SDL_CONTROLLERDEVICEREMAPPED);
		state.set_field("FINGERMOTION", SDL_FINGERMOTION);
		state.set_field("FINGERMOTION", SDL_FINGERMOTION);
		state.set_field("FINGERMOTION", SDL_FINGERMOTION);
		state.set_field("DOLLARGESTURE", SDL_DOLLARGESTURE);
		state.set_field("DOLLARRECORD", SDL_DOLLARRECORD);
		state.set_field("MULTIGESTURE", SDL_MULTIGESTURE);
		state.set_field("CLIPBOARDUPDATE", SDL_CLIPBOARDUPDATE);
		state.set_field("DROPFILE", SDL_DROPFILE);
		state.set_field("USEREVENT", SDL_USEREVENT);
	}
}